import React, { useEffect, useState } from 'react';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { offerApi } from '../services/offer.api';
import { useAuth } from '../contexts/AuthContext';
import { Award, CheckCircle2, XCircle, Download, Calendar, MapPin, DollarSign, Send, Mail } from 'lucide-react';

export const OfferLetterPage: React.FC = () => {
  const [offers, setOffers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  useEffect(() => {
    fetchOffers();
  }, []);

  const fetchOffers = async () => {
    try {
      const res = await offerApi.getOffers();
      setOffers(res.data || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleApproveOffer = async (id: string, candidateName: string) => {
    try {
      await offerApi.approveOffer(id);
      alert(`Offer letter for ${candidateName} approved! Email notification dispatched.`);
      await fetchOffers();
    } catch (e: any) {
      alert(e.message || 'Failed to approve offer letter');
    }
  };

  const handleStatusUpdate = async (id: string, status: string) => {
    try {
      await offerApi.updateStatus(id, status);
      await fetchOffers();
    } catch (e: any) {
      alert(e.message || 'Failed to update offer status');
    }
  };

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Official Offer Letters</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">Review compensation packages, benefits, and electronic signatures.</p>
        </div>
      </div>

      <div className="space-y-6">
        {offers.length === 0 ? (
          <Card className="glass-card p-12 text-center space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-slate-800 text-slate-400 flex items-center justify-center mx-auto">
              <Award className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold">No Offer Letters Available</h3>
            <p className="text-sm text-slate-400">Offer letters will appear here once generated by the hiring manager and approved by the recruiter.</p>
          </Card>
        ) : (
          offers.map((offer) => (
            <Card key={offer.id} className="glass-card p-8 space-y-6 border-brand-500/30">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-6">
                <div>
                  <Badge variant="success" className="mb-2">Official Employment Offer</Badge>
                  <h2 className="text-2xl font-extrabold text-white">{offer.position}</h2>
                  <div className="text-xs text-slate-400 mt-1">Prepared for <strong>{offer.candidateName}</strong></div>
                </div>
                <div className="flex items-center gap-3">
                  <Badge
                    variant={
                      offer.status === 'ACCEPTED'
                        ? 'success'
                        : offer.status === 'REJECTED'
                        ? 'danger'
                        : offer.status === 'PENDING_RECRUITER_APPROVAL'
                        ? 'warning'
                        : 'primary'
                    }
                    className="text-sm font-bold px-4 py-1"
                  >
                    {offer.status === 'PENDING_RECRUITER_APPROVAL' ? 'PENDING RECRUITER APPROVAL' : offer.status}
                  </Badge>
                </div>
              </div>

              {/* Offer Key Attributes */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm bg-slate-900/60 p-4 rounded-2xl border border-slate-800">
                <div className="space-y-1">
                  <span className="text-xs font-semibold text-slate-400 uppercase">Annual Salary</span>
                  <div className="text-xl font-bold text-emerald-400 flex items-center gap-1">
                    <DollarSign className="w-5 h-5" /> ${offer.salary?.toLocaleString()} / year
                  </div>
                </div>
                <div className="space-y-1">
                  <span className="text-xs font-semibold text-slate-400 uppercase">Start Date</span>
                  <div className="text-base font-bold text-white flex items-center gap-1.5">
                    <Calendar className="w-4 h-4 text-brand-500" /> {new Date(offer.joiningDate).toLocaleDateString()}
                  </div>
                </div>
                <div className="space-y-1">
                  <span className="text-xs font-semibold text-slate-400 uppercase">Workplace Location</span>
                  <div className="text-base font-bold text-white flex items-center gap-1.5">
                    <MapPin className="w-4 h-4 text-indigo-500" /> {offer.location}
                  </div>
                </div>
              </div>

              {/* Benefits */}
              <div className="space-y-3">
                <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">Included Compensation Benefits</h4>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
                  {(offer.benefits || []).map((b: string) => (
                    <li key={b} className="flex items-center gap-2 p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-300">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Actions */}
              <div className="pt-4 border-t border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <Button variant="outline" size="sm">
                  <Download className="w-4 h-4 mr-1.5" /> Download Official PDF
                </Button>

                {/* Recruiter / Admin approval button if pending */}
                {(user?.role === 'RECRUITER' || user?.role === 'ADMIN') && offer.status === 'PENDING_RECRUITER_APPROVAL' && (
                  <Button variant="primary" size="sm" onClick={() => handleApproveOffer(offer.id, offer.candidateName)}>
                    <Send className="w-4 h-4 mr-1.5" /> Approve & Dispatch Offer (+ Email)
                  </Button>
                )}

                {/* Candidate Accept/Decline button if sent */}
                {user?.role === 'CANDIDATE' && offer.status === 'SENT' && (
                  <div className="flex items-center gap-3">
                    <Button variant="danger" size="sm" onClick={() => handleStatusUpdate(offer.id, 'REJECTED')}>
                      <XCircle className="w-4 h-4 mr-1" /> Decline Offer
                    </Button>
                    <Button variant="primary" size="sm" onClick={() => handleStatusUpdate(offer.id, 'ACCEPTED')}>
                      <CheckCircle2 className="w-4 h-4 mr-1" /> Accept Employment Offer
                    </Button>
                  </div>
                )}
              </div>
            </Card>
          ))
        )}
      </div>
    </div>
  );
};
